FROM nginx

WORKDIR /home

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./scrpt.sh /home

RUN adduser --disabled-password --gecos "" debik \
    && chmod 777 scrpt.sh \
    && chmod u-s /usr/bin/chfn \
    && chmod u-s /usr/bin/chsh \
    && chmod u-s /usr/bin/passwd \
    && chmod u-s /usr/bin/su \
    && chmod u-s /usr/bin/gpasswd \
    && chmod u-s /usr/bin/umount \
    && chmod u-s /usr/bin/newgrp \
    && chmod u-s /usr/bin/mount \
    && chmod g-s /usr/bin/expiry \
    && chmod g-s /usr/bin/chage \
    && chmod g-s /usr/bin/wall \
    && chmod g-s /usr/bin/unix_chkpwd \
    && touch /var/run/nginx.pid \
    && chown -R debik:debik /var/run/nginx.pid \
    && chown -R debik:debik /var/log/nginx \
    && chown -R debik:debik /var/cache/nginx

USER debik

HEALTHCHECK NONE
ENTRYPOINT [ "./scrpt.sh" ]