FROM nginx

WORKDIR /home

USER root

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./main.c /home/main.c
COPY ./scrpt.sh /home

RUN apt update && apt install -y gcc libfcgi-dev spawn-fcgi
RUN chmod 777 scrpt.sh

EXPOSE 80

ENTRYPOINT [ "./scrpt.sh" ]
